global:
  imagePullSecrets: []
  serviceAccount:
    create: true
    name: barkuni-app-sa
    rules:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list"]
services:
  - name: barkuni-app
    enabled: true
    image:
      repository: 156444772887.dkr.ecr.us-east-1.amazonaws.com/barkuni-app
      tag: "7402518"
      pullPolicy: Always
    port: 8000
    ingress:
      enabled: true
      host: barkuni.nya-solutions.com
      path: /
      annotations:
        kubernetes.io/ingress.class: nginx
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
# Additional services can be defined in the same pattern
