global:
  imagePullSecrets: []
services:
  - name: barkuni-app
    enabled: true
    image:
      repository: 156444772887.dkr.ecr.us-east-1.amazonaws.com/barkuni-app
      tag: 6ec7848
      pullPolicy: Always
    port: 8000
    ingress:
      enabled: true
      host: barkuni.nya-solutions.com
      path: /
      annotations:
        kubernetes.io/ingress.class: nginx
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    serviceAccount:
      create: true
    rbac:
      create: true
      rules:
        - apiGroups: [""]
          resources: ["pods"]
          verbs: ["get", "list"]
# Additional services can be defined in the same pattern
