{{- range .Values.services }}
{{- if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name | quote }}
  labels:
    app: {{ .name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name | quote }}
  template:
    metadata:
      labels:
        app: {{ .name | quote }}
    spec:
      {{- if $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $.Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .port }}
          resources:
            {{- toYaml .resources | nindent 12 }}
      serviceAccountName: {{ if .serviceAccount.create }}{{ .name }}-sa{{ else }}"default"{{ end }}
{{- end }}
{{- end }}
