{{- range .Values.services }}
{{- if .serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}-sa
---
{{- if .rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .name }}-role
rules:
  {{- toYaml .rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .name }}-role
subjects:
- kind: ServiceAccount
  name: {{ .name }}-sa
{{- end }}
{{- end }}
{{- end }}
