{{- range .Values.services }}
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name | quote }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .name | quote }}
{{- end }}
{{- end }}
