name: CI

on:
  pull_request:
    branches:
      - master
    paths:
      - 'api/app/**'
      - 'api/tests/**'
      - '.github/workflows/ci.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.14'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          cd api
          python -m pytest
